apiVersion: v1
kind: Service
metadata:
  name: rx-eurake-server-03-service
spec:
  type: NodePort
  ports:
    - port: 1113
      nodePort: 30113
      targetPort: 1113
      protocol: TCP
  selector:
    name: rx-eurake-server-03