apiVersion: v1
kind: Service
metadata:
  name: rx-config-server-service
spec:
  type: NodePort
  ports:
    - port: 9999
      nodePort: 30999
      targetPort: 9999
      protocol: TCP
  selector:
    name: rx-config-server