apiVersion: v1
kind: Service
metadata:
  name: rx-zipkin-server-service
spec:
  type: NodePort
  ports:
    - port: 9411
      nodePort: 30411
      targetPort: 9411
      protocol: TCP
  selector:
    name: rx-zipkin-server