apiVersion: v1
kind: Service
metadata:
  name: rx-eurake-server-01-service
spec:
  type: NodePort
  ports:
    - port: 1111
      nodePort: 30111
      targetPort: 1111
      protocol: TCP
  selector:
    name: rx-eurake-server-01